services:
  - type: web
    name: habit-tracker-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        sync: false
